### ISSUE TITLE
App "Fractal Note" cannot be installed because it is not compatible with this version of the server.

### ISSUE THREAD

**Issue by ghost** [alboro/fractalnote#2]
During install (sudo -u www-data ./occ app:enable fractalnote) I received the following err message:

"App "Fractal Note" cannot be installed because it is not compatible with this version of the server."

Nextcloud 13.0.0
PHP 7.0.27-0+deb9u1

**Comment by alboro** [comment]
Sorry for late response: will fix by the end of the week.

**Comment by ghost** [comment]
Thanks!

**Comment by ghost** [comment]
Hi, Is there any update about this issue? Thanks

**Comment by alboro** [comment]
> 
> Hi, Is there any update about this issue? Thanks

@kissrichard, it's almost year passed, sorry for that. I've just removed "max-version" directive. But did't have enough time to install nextcloud 13\14\15 versions. So, can you please try on your version and share your feedback? Thank you!

**Comment by alboro** [comment]
Tested in 13 version. Works. 14 have bugs, will fix soon..

**Comment by alboro** [comment]
BTW: fractalnote was fixed also for nextcloud 14/15 versions
