### ISSUE TITLE
No open ctb files

### ISSUE THREAD

**Issue by kib373417** [alboro/fractalnote#3]
Hi
I installed the application (Nextcloud 15.0.5), but when I try to open a .ctb (file created in CheryTree 0.38.4) file in nextcloud, I constantly get:
"Please, go to files list, find the CherryTree (.ctb) file and make single click on it to see its contents. "

**Comment by alboro** [comment]
@kib373417, thank you for reporting. I'll try to create & open. BTW: have you added into {nextcloud-install-folder}/config/mimetypemapping.json such content (?):
```
{
    "ctb": ["application/cherrytree-ctb"]
}
```

**Comment by kib373417** [comment]
Yes, I had it added.
I created as in the instructions.

GNU nano 2.7.4       File: /var/www/nextcloud/config/mimetypemapping.json                                                                                          
{
    "km": [
        "application/km"
    ],
    "ctb": ["application/cherrytree-ctb"]
}


Here is a test phpunit:
root@debian:/var/www/nextcloud/apps/fractalnote# phpunit -c phpunit.xml
PHPUnit 5.4.6 by Sebastian Bergmann and contributors.
.                                                                   1 / 1 (100%)
Time: 445 ms, Memory: 12.00MB
OK (1 test, 3 assertions)

I click the file .ctb and go page: "Please, go to files list, find the CherryTree (.ctb) file and make single click on it to see its contents. "   ((

**Comment by alboro** [comment]
@kib373417, have you tried absolute url from my instructions? This:
`https://[your-cloud-server]/index.php/apps/fractalnote?f=[filename].ctb`
`[filename].ctb` is full path to the target file from your nextcloud's virtual home directory.
What does this url show to you?

**Comment by kib373417** [comment]
Checked the link, again the same page: 
"Please, go to files list, find the CherryTree (.ctb) file and make single click on it to see its contents. "

**Comment by alboro** [comment]
@kib373417, may be you could share with me such ctb file, which cannot be open by my program?

**Comment by kib373417** [comment]
At first I thought so too. I copied your demo.ctb. He also did not open.
Сначала я тоже так подумал. Я скопировал ваш демо.стб. Он тоже не открылся.

**Comment by alboro** [comment]
@kib373417, may be `extension=pdo_sqlite.so` is disabled in your system? If no, then i need your nextcloud logs.

**Comment by kib373417** [comment]
Thank you. Installed php-sqlite. And wrote in php.ini "extension = pdo_sqlite.so". It all worked!

One more question: is it possible to create folders(node) and subfolders in the ctb file or only read it?
In the demo.ctb, I see that people have created their nodes, but in the web interface I do not see this function.

**Comment by alboro** [comment]
@kib373417, great ) sorry, i will update readme, that sqlite is needed.

> is it possible to create folders(node) and subfolders in the ctb file or only read it

This bug is actual for nextcloud14/15 versions. I've fixed it for 15 version and will fix today for 14. So you sould just run something like:
`cd /var/www/nextcloud-15/apps/fractalnote`
`git pull`
And after that right-click over folder tree will activate context menu.

**Comment by kib373417** [comment]
Everything turned out, thanks for the program!
Sorry to open it, but the TAB button when editing text will work, indent?

**Comment by alboro** [comment]
@kib373417, tab will not work, but you can use spaces :) Frectalnote supports only text nodes for now.
