### ISSUE TITLE
cherry tree interface 

### ISSUE THREAD

**Issue by benjithereborn** [alboro/fractalnote#5]
First of all nice project but the lack of features are an issue in my opinion. So I think it would make more sense to take the already existing layout and slap it in a browser, and in a another step change  the GUI so it's usable on a mobile, in that all functions would work, or am i missing something?

**Comment by alboro** [comment]
@benjithereborn, existing layout exists only in original app. So, i cannot just take it into browser. To do so this layout must be re-implemented.
